services:
  pgsql:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    hostname: ${POSTGRES_HOSTNAME}
    ports:
      - 5432:5432
    #restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_USER_PASS}
    volumes:
      - postgres-volumes:/var/lib/postgresql/data"

volumes:
  postgres-volumes:
